### ISSUE TITLE
Icons | Flutter.link

### ISSUE THREAD

**Issue by flyou** [flyou/flyou.github.io#5]
http://flutter.link/2018/03/09/Icons/

**Comment by wozhizhizhi** [comment]
写的很好,好像很久没更新了

**Comment by ipv4sec** [comment]
博主我想问下 我下载的是[阿里的图标](http://iconfont.cn/)， 代码是

`Icon(IconData(0xe875, fontFamily: "iconfont"), color: Colors.blue, size: 100.0)`
```
  fonts:
    - family: iconfont
      fonts:
        - asset: resources/iconfont.ttf
```
却显示

![2018-9-28 23-41-4](https://user-images.githubusercontent.com/29883657/46218737-fbedf280-c377-11e8-994b-35e7c399a679.png)

这是怎么回事啊
